version: 0.2

phases:
  build:
    commands:
      - echo Deploying Kubernetes ConfigMaps and Services...
      - make postgres-install-prod
      - make k8s-prod-apply

artifacts:
  files:
    - "**/*"
  discard-paths: yes
