version: 0.2

phases:
  pre_build:
    commands:
      - echo Building Connect to EKS...
      - make eks-connect
  build:
    commands:
      - echo Deploying Kubernetes ConfigMaps and Services...
      - make postgres-install-prod
      - make k8s-prod-apply

artifacts:
  files:
    - "**/*"
  discard-paths: yes
