apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: coworking
type: Opaque
data:
  DB_USERNAME: bG9jYWx1c2Vy
  DB_PASSWORD: bG9jYWxwYXNzd29yZA==
  POSTGRES_SUPERUSER_PASSWORD: YWRtaW5fcGFzc3dvcmQ=
